import React from 'react';

interface EmptyStateProps {
  message?: string;
  icon?: string;
  className?: string;
}

/**
 * EmptyState — P1-3 data-missing placeholder.
 *
 * Displayed when a view's data is null (file not yet generated by the pipeline).
 * Shows a friendly message like "本阶段数据待生成" with an icon.
 *
 * This is critical for the incremental build mechanism: early pipeline steps
 * will have null data for later stages, and these components must not crash.
 */
export const EmptyState: React.FC<EmptyStateProps> = ({
  message = '本阶段数据待生成',
  icon = '⏳',
  className = '',
}) => {
  return (
    <div className={`flex flex-col items-center justify-center py-16 text-center ${className}`}>
      <div className="text-4xl mb-3 opacity-50">{icon}</div>
      <div className="text-text2 text-sm">{message}</div>
      <div className="text-text2 text-2xs mt-1">管线推进到此步骤后，数据将自动填充</div>
    </div>
  );
};
