import React, { useMemo } from 'react';
import { marked } from 'marked';
import type { MarkedOptions } from 'marked';

interface MarkdownRendererProps {
  content: string;
  className?: string;
}

// Configure marked once
marked.setOptions({
  async: false,
  gfm: true,
  breaks: false,
});

/**
 * MarkdownRenderer — renders markdown content using inline marked.js.
 *
 * The marked library is bundled by Vite and inlined into the single-file HTML
 * by vite-plugin-singlefile, ensuring file:// offline availability.
 *
 * Content is trusted (generated by the pipeline agent), so no DOMPurify sanitization
 * is applied. If user input rendering is added later, DOMPurify should be introduced.
 */
export const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({ content, className = '' }) => {
  const html = useMemo(() => {
    try {
      // In marked v14, parse() without explicit options returns string | Promise<string>.
      // Pass {async: false} explicitly to guarantee synchronous string return.
      const opts: MarkedOptions & { async: false } = { async: false } as MarkedOptions & { async: false };
      const result = marked.parse(content || '# 内容加载失败', opts);
      // Defensive: ensure we always produce a string for dangerouslySetInnerHTML
      if (typeof result === 'string') {
        return result;
      }
      // If a Promise leaked through (shouldn't happen with async:false), render synchronously
      return String(result);
    } catch (err) {
      return `<p style="color: var(--red)">Markdown 渲染失败: ${String(err)}</p>`;
    }
  }, [content]);

  return (
    <div
      className={`md-content ${className}`}
      dangerouslySetInnerHTML={{ __html: html }}
    />
  );
};
